// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9k6lvdhkI14TWm4y3g7iJV0zjlsA4Tws',
    appId: '1:560234316268:web:d70b96bc633aea604640c9',
    messagingSenderId: '560234316268',
    projectId: 'quiz-9ffc5',
    authDomain: 'quiz-9ffc5.firebaseapp.com',
    storageBucket: 'quiz-9ffc5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwIPcvJC8j8zkSEYLrGuOO85IU_ladx8A',
    appId: '1:560234316268:android:b6e2454aa1a7b43f4640c9',
    messagingSenderId: '560234316268',
    projectId: 'quiz-9ffc5',
    storageBucket: 'quiz-9ffc5.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9k6lvdhkI14TWm4y3g7iJV0zjlsA4Tws',
    appId: '1:560234316268:web:b525e79bd963de314640c9',
    messagingSenderId: '560234316268',
    projectId: 'quiz-9ffc5',
    authDomain: 'quiz-9ffc5.firebaseapp.com',
    storageBucket: 'quiz-9ffc5.firebasestorage.app',
  );
}
